name: version_updater
description: Automatically update the js version of flutter web.
version: 1.0.0
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  yaml: ^3.1.2
dev_dependencies:
  lints: ^4.0.0
